config/routes.rb
Rails.application.routes.draw do
  root "tasks#index"

  resources :tasks, except: %i[show destroy]
  resources :kinds, except: %i[show destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kind.rb
class Kind < ApplicationRecord
  def self.min_size
    20
  end

  def color; "blue"; end

  validates :name, length: { minimum: 5 }, presence: true, uniqueness: true
  validates :size, numericality: { greater_than_or_equal_to: min_size }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :kind

  validates :name, presence: true
  validates :description, presence: true

  # missing category here with: development, backlog, review, administrative
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  def index
    @kinds = Kind.all
  end

  def new
    @kind = Kind.new
  end

  def edit
    kind = Kind.find(params[:id])
    @kind   = kind
  end

  def create
    kind = Kind.create(kind_params)
    if kind.valid?
      if kind.save
        flash[:notice] = "Kind good enough!"
        redirect_to kinds_path
      else
        @kind = kind
        render :new
      end
    else
      flash[:notice] = "Kind name should be 5 characters length and size at least 20!"
      @kind = kind
      render :new
    end
  end

  def update
    @kind = Kind.find(params[:id])
    @kind.update(kind_params)
    !@kind.valid? && (return render "edit")
    redirect_to kinds_path
  end

  private

  def kind_params
    params.require(:kind).permit(:name, :active, :size)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

	def edit
		task = Task.find(params[:id])
		@task   = task
	end

  def create
    task = Task.create(task_params)
    if task.valid?
      if task.save
        flash[:notice] = "Task good enough!"
        redirect_to tasks_path
      else
        @task = task
        render :new
      end
    else
      flash[:notice] = "Task not filled in properly"
      @task = task
      render :new
    end
  end

	def update
		@task = Task.find(params[:id])
		@task.update(task_params)
		!@task.valid? && (return render "edit")
		redirect_to tasks_path
	end

  private

  def task_params
    params.require(:task).permit(:name, :category, :delivery_at, :description, :kind_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/kinds/_form.html.erb
<%= form_for kind, html: { class: "form" } do |form| %>
  <% if kind.errors.any? %>
    <p><%= pluralize(kind.errors.count, "error") %> prohibited this kind from being saved:</p>

      <ul>
        <% kind.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
      <span class="form-message required">This is a required field.</span>
    </div>

    <div class="field">
      <label> Size </label>      <%= form.text_field :size %>
    </div>

    <div class="field">
      <%= form.label :active %>
      <%= form.check_box :active %>
    </div>
  </fieldset>

  <div class="form-actions">
    <%= link_to "Cancel", kinds_path, class: "other-action" %>
    <%= form.submit %>
  </div>
<% end %>

app/views/kinds/edit.html.erb
<h2>Editing Kind</h2>

<%= render "form", kind: @kind %>

app/views/kinds/index.html.erb
<%= link_to "Go to tasks", tasks_path %>

<h2>Kinds</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Active</th>
      <th>Size</th>
      <th><%= link_to "Add new kind", new_kind_path %></th>
    </tr>
  </thead>

  <tbody>
    <% @kinds.each do |kind| %>
      <tr>
        <td><%= kind.name %></td>
        <td class="<%= kind.color %>" ><%= kind.active? %></td>
        <td class="<%= kind.color %>" ><%= kind.size %></td>
        <td><%= link_to "Edit", edit_kind_path(kind) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/kinds/new.html.erb
<h2>New Kind</h2>

<%= render "form", kind: @kind %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for task, html: { class: "form" } do |form| %>
  <% if task.errors.any? %>
    <p><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</p>

      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
      <span class="form-message required">This is a required field.</span>
    </div>

    <div class="field">
      <%= form.label :category %>
      <%= form.select :category, options_for_select([["development", "development"], ["backlog", "backlog"], ["review", "review"], ["administrative", "administrative"]]) %>
    </div>

    <div class="field">
      <%= form.label :delivery_at %>
      <%= form.datetime_select :delivery_at %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>

    <div class="field">
      <%= form.label :kind_id %>
      <%= form.select :kind_id, Kind.all.collect{|p| [p.id, p.id]} %>
    </div>
  </fieldset>

  <div class="form-actions">
    <%= link_to "Cancel", tasks_path, class: "other-action" %>
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h2>Editing Task</h2>

<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<%= link_to "Go to kinds", kinds_path %>

<h2>Tasks</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Kind</th>
      <th>Category</th>
      <!-- Should we add more thinsg to the table? -->
      <th><%= link_to "Add new task", new_task_path %></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name%></td>
        <td><%= task.kind_id%></td>
        <td><%= task.category%></td>
        <td><%= link_to "Edit", edit_task_path(task) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<h2>New Task</h2>

<%= render "form", task: @task %>